# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_enseignantclasse_gid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video')),
                ('tt', models.TextField(default='WEBTT\n\n')),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.EnseignantClasse')),
            ],
        ),
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt', models.TextField()),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Atelier')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Etudiant')),
            ],
        ),
    ]
