# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20170129_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travail',
            name='tt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
